services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: oktal
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: oktaldb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oktal -d oktaldb"]
      interval: 5s
      timeout: 5s
      retries: 5