"""add MemoryCHunk with source_type

Revision ID: 528c2c8f03a3
Revises: ea157ce75be7
Create Date: 2025-06-22 22:25:03.404928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "528c2c8f03a3"
down_revision: Union[str, None] = "ea157ce75be7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    memory_source_type_enum = sa.Enum("CHAT_MESSAGE", "EMAIL", "TELEGRAM", "WHATSAPP", "SLACK", name="memorysourcetype")
    memory_source_type_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "memory_chunks",
        sa.Column(
            "source_type",
            memory_source_type_enum,
            nullable=True,
        ),
    )
    op.add_column("memory_chunks", sa.Column("source_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memory_chunks", "source_id")
    op.drop_column("memory_chunks", "source_type")
    # ### end Alembic commands ###
    sa.Enum(name="memorysourcetype").drop(op.get_bind())
